# Theming
font: JetBrainsMono Nerd Font 12
background: "#282828d0"
color: "#fbf1c7"
border: "#8ec07c"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# # namespace to use for the layer shell surface
# namespace: "wlr_which_key"

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
# inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "f"
    desc: Firefox
    cmd: firefox --new-window
  - key: "k"
    desc: KeePassXC
    cmd: keepassxc
  - key: "m"
    desc: Messages and misc
    submenu:
    - key: "s"
      desc: Signal
      cmd: signal-desktop
    - key: "w"
      desc: WhatsApp
      cmd: firefox --new-window https://web.whatsapp.com/
    - key: "g"
      desc: Gmail
      cmd: firefox --new-window https://mail.google.com/mail/u/0/#inbox
    - key: "v"
      desc: Google Voice
      cmd: firefox --new-window https://voice.google.com/u/0/messages
    - key: "y"
      desc: YouTube Music
      cmd: firefox --new-window https://music.youtube.com/
  - key: "p"
    desc: Power
    submenu:
     - key: "p"
       desc: Power Off
       cmd: shutdown now
  # - key: "t"
  #   desc: Tasks 
  #   cmd: super-productivity
